server:
  port: 8080
spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/database_topicos?serverTimezone=UTC
    username: root
    password: ''
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update